import { Bed } from "../types/bed";
import { Patient } from "../types/patient";
import { Sensor } from "../types/sensor";
import { Building } from "../types/building";
import { Ward } from "../types/ward";
import { Room } from "../types/room";
import { Notification } from "../types/notification";
import { User } from "../types/user";

export const MOCK_BUILDINGS: Building[] = [
  {
    building_id: 1,
    building_name: "อาคารเฉลิมพระเกียรติ 80 พรรษา",
    floor: [
      {
        floor_id: 4,
        floor_number: 4,
        building_id: 1,
        wards: [],
      },
    ],
  },
];

export const MOCK_FLOOR = MOCK_BUILDINGS[0].floor![0];

export const MOCK_WARD: Ward = {
  ward_id: 1,
  ward_name: "วอร์ดอายุรกรรมโรคหัวใจและหลอดเลือด (Cardiology Ward 4B)",
  floor: MOCK_FLOOR,
};

export const MOCK_ROOMS: Room[] = [
  {
    room_id: 101,
    room_name: "ห้อง 401 (ผู้ป่วยวิกฤต/ติดตามใกล้ชิด)",
    ward_id: 1,
    ward: MOCK_WARD,
    floor: MOCK_FLOOR,
  },
  {
    room_id: 102,
    room_name: "ห้อง 402 (ผู้ป่วยพักฟื้น)",
    ward_id: 1,
    ward: MOCK_WARD,
    floor: MOCK_FLOOR,
  },
  {
    room_id: 103,
    room_name: "ห้อง 403 (ห้องพิเศษเดี่ยว)",
    ward_id: 1,
    ward: MOCK_WARD,
    floor: MOCK_FLOOR,
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    patient_id: 1,
    patient_name: "นายสมชาย พัฒนกิจ",
    patient_age: 68,
    patient_gender: "ชาย",
    patient_dob: "12/04/2501 (1958-04-12)",
    patient_disease: "กล้ามเนื้อหัวใจขาดเลือด (CAD), ความดันโลหิตสูง",
    patient_status: "เข้ารับการรักษา",
    patient_date_in: "28/08/2026",
    patient_bloodtype: "O+",
    image_path: "/src/assets/default.png",
  },
  {
    patient_id: 2,
    patient_name: "นางมาลี ทองคำ",
    patient_age: 74,
    patient_gender: "หญิง",
    patient_dob: "05/11/2495 (1952-11-05)",
    patient_disease: "ภาวะหัวใจล้มเหลว (CHF), เสี่ยงต่อการพลัดตกหกล้ม",
    patient_status: "เฝ้าระวังพิเศษ",
    patient_date_in: "29/08/2026",
    patient_bloodtype: "B+",
    image_path: "/src/assets/default.png",
  },
  {
    patient_id: 3,
    patient_name: "นายวิชัย เกียรติสุข",
    patient_age: 59,
    patient_gender: "ชาย",
    patient_dob: "18/02/2510 (1967-02-18)",
    patient_disease: "หัวใจเต้นผิดจังหวะ (Atrial Fibrillation)",
    patient_status: "เข้ารับการรักษา",
    patient_date_in: "30/08/2026",
    patient_bloodtype: "A+",
    image_path: "/src/assets/default.png",
  },
  {
    patient_id: 4,
    patient_name: "นางสมศรี ประเสริฐสุข",
    patient_age: 81,
    patient_gender: "หญิง",
    patient_dob: "24/09/2488 (1945-09-24)",
    patient_disease: "หลังผ่าตัดข้อสะโพก, อัมพฤกษ์ซีกซ้าย",
    patient_status: "เฝ้าระวังพิเศษ",
    patient_date_in: "31/08/2026",
    patient_bloodtype: "AB+",
    image_path: "/src/assets/default.png",
  },
  {
    patient_id: 5,
    patient_name: "นายเอกชัย นามสมมุติ",
    patient_age: 62,
    patient_gender: "ชาย",
    patient_dob: "14/07/2507 (1964-07-14)",
    patient_disease: "ถุงลมโป่งพอง (COPD), ภาวะขาดออกซิเจนเรื้อรัง",
    patient_status: "เข้ารับการรักษา",
    patient_date_in: "01/09/2026",
    patient_bloodtype: "O-",
    image_path: "/src/assets/default.png",
  },
  {
    patient_id: 6,
    patient_name: "นางกานดา รักษ์ดี",
    patient_age: 65,
    patient_gender: "หญิง",
    patient_dob: "30/03/2504 (1961-03-30)",
    patient_disease: "โรคไตวายเรื้อรังระยะ 4, เบาหวานชนิดที่ 2",
    patient_status: "เข้ารับการรักษา",
    patient_date_in: "01/09/2026",
    patient_bloodtype: "B-",
    image_path: "/src/assets/default.png",
  },
];

const now = new Date();
const todayISO = now.toISOString().split("T")[0];

export const createMockSensors = (bedId: number): Sensor[] => [
  {
    sensor_id: bedId * 10 + 1,
    bed_id: bedId,
    sensor_name: "Heart Rate",
    sensor_type: "heart_rate",
    sensor_status: true,
    sensor_unit: "bpm",
    sensor_mac_i: `AA:BB:CC:DD:0${bedId}:01`,
    history_value_sensor: Array.from({ length: 24 }, (_, i) => ({
      history_value_sensor_id: i + 1,
      sensor_id: bedId * 10 + 1,
      history_value_sensor_value: (74 + Math.sin(i / 2) * 5 + (bedId % 3)).toFixed(0),
      history_value_sensor_time: `${todayISO}T${String(i).padStart(2, "0")}:00:00.000Z`,
      notification_level: 0,
    })),
  },
  {
    sensor_id: bedId * 10 + 2,
    bed_id: bedId,
    sensor_name: "SpO2",
    sensor_type: "spo2",
    sensor_status: true,
    sensor_unit: "%",
    sensor_mac_i: `AA:BB:CC:DD:0${bedId}:02`,
    history_value_sensor: Array.from({ length: 24 }, (_, i) => ({
      history_value_sensor_id: i + 30,
      sensor_id: bedId * 10 + 2,
      history_value_sensor_value: (98 + (i % 2)).toFixed(0),
      history_value_sensor_time: `${todayISO}T${String(i).padStart(2, "0")}:00:00.000Z`,
      notification_level: 0,
    })),
  },
  {
    sensor_id: bedId * 10 + 3,
    bed_id: bedId,
    sensor_name: "Respiration",
    sensor_type: "respiration",
    sensor_status: true,
    sensor_unit: "rpm",
    sensor_mac_i: `AA:BB:CC:DD:0${bedId}:03`,
    history_value_sensor: Array.from({ length: 24 }, (_, i) => ({
      history_value_sensor_id: i + 60,
      sensor_id: bedId * 10 + 3,
      history_value_sensor_value: (16 + (i % 3)).toFixed(0),
      history_value_sensor_time: `${todayISO}T${String(i).padStart(2, "0")}:00:00.000Z`,
      notification_level: 0,
    })),
  },
  {
    sensor_id: bedId * 10 + 4,
    bed_id: bedId,
    sensor_name: "Bed & Sleep",
    sensor_type: "bed_sensor",
    sensor_status: true,
    sensor_unit: "State",
    sensor_mac_i: `AA:BB:CC:DD:0${bedId}:04`,
    history_value_sensor: [
      {
        history_value_sensor_id: 101,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "นอนหงาย",
        history_value_sensor_time: `${todayISO}T00:00:00.000Z`,
        notification_level: 0,
      },
      {
        history_value_sensor_id: 102,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "ตะแคงขวา",
        history_value_sensor_time: `${todayISO}T02:30:00.000Z`,
        notification_level: 0,
      },
      {
        history_value_sensor_id: 103,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "ตะแคงซ้าย",
        history_value_sensor_time: `${todayISO}T05:15:00.000Z`,
        notification_level: 0,
      },
      {
        history_value_sensor_id: 104,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "นั่งบนเตียง",
        history_value_sensor_time: `${todayISO}T06:45:00.000Z`,
        notification_level: 0,
      },
      {
        history_value_sensor_id: 105,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "ไม่อยู่ที่เตียง",
        history_value_sensor_time: `${todayISO}T07:15:00.000Z`,
        notification_level: 0,
      },
      {
        history_value_sensor_id: 106,
        sensor_id: bedId * 10 + 4,
        history_value_sensor_value: "นอนหงาย",
        history_value_sensor_time: `${todayISO}T08:00:00.000Z`,
        notification_level: 0,
      },
    ],
  },
];

export const MOCK_BEDS: Bed[] = [
  {
    bed_id: 1,
    bed_name: "เตียง 01 (Bed 01)",
    bed_activated: true,
    room: MOCK_ROOMS[0],
    room_id: 101,
    patient_id: 1,
    patient: MOCK_PATIENTS[0],
    sensors: createMockSensors(1),
    selectedShowSensorId: [11, 12, 13],
  },
  {
    bed_id: 2,
    bed_name: "เตียง 02 (Bed 02 - เฝ้าระวัง)",
    bed_activated: true,
    room: MOCK_ROOMS[0],
    room_id: 101,
    patient_id: 2,
    patient: MOCK_PATIENTS[1],
    sensors: createMockSensors(2),
    selectedShowSensorId: [21, 22, 23],
  },
  {
    bed_id: 3,
    bed_name: "เตียง 03 (Bed 03)",
    bed_activated: true,
    room: MOCK_ROOMS[1],
    room_id: 102,
    patient_id: 3,
    patient: MOCK_PATIENTS[2],
    sensors: createMockSensors(3),
    selectedShowSensorId: [31, 32, 33],
  },
  {
    bed_id: 4,
    bed_name: "เตียง 04 (Bed 04 - เฝ้าระวัง)",
    bed_activated: true,
    room: MOCK_ROOMS[1],
    room_id: 102,
    patient_id: 4,
    patient: MOCK_PATIENTS[3],
    sensors: createMockSensors(4),
    selectedShowSensorId: [41, 42, 43],
  },
  {
    bed_id: 5,
    bed_name: "เตียง 05 (Bed 05)",
    bed_activated: true,
    room: MOCK_ROOMS[2],
    room_id: 103,
    patient_id: 5,
    patient: MOCK_PATIENTS[4],
    sensors: createMockSensors(5),
    selectedShowSensorId: [51, 52, 53],
  },
  {
    bed_id: 6,
    bed_name: "เตียง 06 (Bed 06)",
    bed_activated: true,
    room: MOCK_ROOMS[2],
    room_id: 103,
    patient_id: 6,
    patient: MOCK_PATIENTS[5],
    sensors: createMockSensors(6),
    selectedShowSensorId: [61, 62, 63],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    notification_id: 1,
    sensor_notifications_config_id: 1,
    log_bed_patient_sensor_id: 101,
    notification_category: "Emergency",
    notification_accepted: false,
    notification_successed: false,
    notification_createdate: new Date().toISOString(),
    sensor_notifications_config: {
      sensor_notifications_config_id: 1,
      sensor_id: 14,
      sensor_notifications_config_name: "ตรวจพบการเคลื่อนไหวผิดปกติ (เสี่ยงล้ม/ตกเตียง)",
      sensor_notifications_config_unit: "State",
      sensor_notifications_config_status: true,
      sensor_notifications_config_type: "Emergency",
      sensor_notifications_config_event: "ตรวจพบการเคลื่อนไหวผิดปกติ (เสี่ยงล้ม/ตกเตียง)",
    } as any,
  },
  {
    notification_id: 2,
    sensor_notifications_config_id: 2,
    log_bed_patient_sensor_id: 102,
    notification_category: "SOS",
    notification_accepted: false,
    notification_successed: false,
    notification_createdate: new Date(Date.now() - 15 * 60000).toISOString(),
    sensor_notifications_config: {
      sensor_notifications_config_id: 2,
      sensor_id: 11,
      sensor_notifications_config_name: "อัตราการเต้นของหัวใจสูงผิดปกติ (>100 bpm)",
      sensor_notifications_config_unit: "bpm",
      sensor_notifications_config_status: true,
      sensor_notifications_config_type: "SOS",
      sensor_notifications_config_event: "อัตราการเต้นของหัวใจสูงผิดปกติ (>100 bpm)",
    } as any,
  },
  {
    notification_id: 3,
    sensor_notifications_config_id: 3,
    log_bed_patient_sensor_id: 103,
    notification_category: "Warning",
    notification_accepted: true,
    notification_successed: true,
    notification_createdate: new Date(Date.now() - 60 * 60000).toISOString(),
    sensor_notifications_config: {
      sensor_notifications_config_id: 3,
      sensor_id: 12,
      sensor_notifications_config_name: "ระดับออกซิเจนในเลือดลดลงต่ำกว่า 95%",
      sensor_notifications_config_unit: "%",
      sensor_notifications_config_status: true,
      sensor_notifications_config_type: "Warning",
      sensor_notifications_config_event: "ระดับออกซิเจนในเลือดลดลงต่ำกว่า 95%",
    } as any,
  },
];

export const MOCK_USERS: User[] = [
  {
    user_id: 1,
    user_username: "mattew.admin",
    user_name: "ภัทรพล จันทร์สง่า (MatTew)",
    user_position: "Admin",
    user_password: "password123",
    ward_id: 1,
    ward: MOCK_WARD,
    image_path: "/src/assets/Male User.png",
  },
  {
    user_id: 2,
    user_username: "dr.sudaporn",
    user_name: "พญ. สุดาพร วัฒนกุล",
    user_position: "Doctor",
    user_password: "password123",
    ward_id: 1,
    ward: MOCK_WARD,
    image_path: "/src/assets/Male User.png",
  },
  {
    user_id: 3,
    user_username: "nurse.waraporn",
    user_name: "พว. วราภรณ์ สุขใจ",
    user_position: "Nurse",
    user_password: "password123",
    ward_id: 1,
    ward: MOCK_WARD,
    image_path: "/src/assets/Nurse_bot.png",
  },
];
